version: "3"

services:
  web:
    build:
      context: src/
    ports:
      - "8000:8000"
    env_file: "src/.env"
    command: >
      sh -c "piccolo migrations forwards all &&
             uvicorn app:create_app --reload --host 0.0.0.0 --port 800"
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=hotei
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - default

networks:
  default: {}